### ISSUE TITLE
Error : No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by pratapladhani** [OfficeDev/O365-JavaScript-GetStarted#1]
GET https://outlook.office365.com/api/v1.0/me/messages
    (anonymous function) @ angular.js:10413
    sendReq @ angular.js:10232
    $get.serverRequest @ angular.js:9944
    processQueue @ angular.js:14454
    (anonymous function) @ angular.js:14470
    $get.Scope.$eval @ angular.js:15719
    $get.Scope.$digest @ angular.js:15530
    $get.Scope.$apply @ angular.js:15824
    done @ angular.js:10263
    completeRequest @ angular.js:10435
    requestLoaded @ angular.js:10376
    
    (index):1 XMLHttpRequest cannot load https://outlook.office365.com/api/v1.0/me/messages. 
    No 'Access-Control-Allow-Origin' header is present on the requested resource. 
    Origin 'http://localhost:8080' is therefore not allowed access. 
    The response had HTTP status code 401. homeController.js:20 
    HTTP request to Mail API failed.

**Comment by martellaj** [comment]
My apologies, @pratapladhani, but I'm just seeing this issue now. I believe you opened this issue during the time CORS support for the Mail API was being slowly rolled out. I'm assuming this is no longer a problem for you so I'll close this issue. Again, sorry for such a huge delay!
